{% set name = "importlab" %}
{% set version = "0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 744bd75d4410744962d203bd1eb71a950b19e8fb8eb5f0b805461dc0a2da329b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - networkx
    - python
    - six

test:
  imports:
    - importlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/importlab
  summary: A library to calculate python dependency graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
