{% set name = "importlab" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 056503329df1ba8f6291a4b548042aa18620ad91d39388ba58044f0fd44ff83e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - networkx
    - python
    - six

test:
  imports:
    - importlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/importlab
  summary: A library to calculate python dependency graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
